export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CLEAR_DATA_TOKEN = "CLEAR_DATA_TOKEN";
export const FECTH_PRODUCT_REQUEST = "FECTH_PRODUCT_REQUEST";
export const FECTH_PRODUCT_SUCCESS = "FECTH_PRODUCT_SUCCESS";
export const FECTH_PRODUCT_FAILURE = "FECTH_PRODUCT_FAILURE";
