export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CLEAR_DATA_TOKEN = "CLEAR_DATA_TOKEN";

export const FECTH_PRODUCT_REQUEST = "FECTH_PRODUCT_REQUEST";
export const FECTH_PRODUCT_SUCCESS = "FECTH_PRODUCT_SUCCESS";
export const FECTH_PRODUCT_FAILURE = "FECTH_PRODUCT_FAILURE";

export const FECTH_CATEGORY_REQUEST = "FECTH_CATEGORY_REQUEST";
export const FECTH_CATEGORY_SUCCESS = "FECTH_CATEGORY_SUCCESS";
export const FECTH_CATEGORY_FAILURE = "FECTH_CATEGORY_FAILURE";

export const FECTH_STORE_REQUEST = "FECTH_STORE_REQUEST";
export const FECTH_STORE_SUCCESS = "FECTH_STORE_SUCCESS";
export const FECTH_STORE_FAILURE = "FECTH_STORE_FAILURE";

export const FECTH_CUSTOMER_REQUEST = "FECTH_CUSTOMER_REQUEST";
export const FECTH_CUSTOMER_SUCCESS = "FECTH_CUSTOMER_SUCCESS";
export const FECTH_CUSTOMER_FAILURE = "FECTH_CUSTOMER_FAILURE";

export const FECTH_MY_INFO_REQUEST = "FECTH_MY_INFO_REQUEST";
export const FECTH_MY_INFO_SUCCESS = "FECTH_MY_INFO_SUCCESS";
export const FECTH_MY_INFO_FAILURE = "FECTH_MY_INFO_FAILURE";
export const FECTH_MY_INFO_UPDATE_REQUEST = "FECTH_MY_INFO_UPDATE_REQUEST";
export const FECTH_MY_INFO_UPDATE_SUCCESS = "FECTH_MY_INFO_UPDATE_SUCCESS";
export const FECTH_MY_INFO_UPDATE_FAILURE = "FECTH_MY_INFO_UPDATE_FAILURE";
